version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install

      - echo Fixing node-sass...
      - npm i --unsafe-perm node-sass
  build:
    commands:
      - echo Compiling and testing the Node.js code...
      - npm run test
  post_build:
    commands:
      - echo Build completed...

artifacts:
  files:
    - .ebextensions/**/*
    - src/**/*
    - package.json
    - package-lock.json
    - yarn.lock
    - node_modules/**/*
    - public/**/*
    - config/**/*

